import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";

import { saveArtifact } from "../utils/artifactStore.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pdfAgent = async (state) => {

  try {
await checkAgentLimit(
    state.userId,
    "pdf"
  );
 await deductCredits(state.userId, "pdf", {
      runId: state.requestId,
      conversationId: state.conversationId,
    });  
    const llm =
      getModel("pdf");

    const aiResponse =
      await llm.invoke(`

Create a professional document about:

${state.prompt}

Rules:

- Generate a professional title.
- Generate introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.

`);

    const rawContent =
      aiResponse?.content?.trim() ||
      state.prompt;

    const lines =
      rawContent
        .split("\n")
        .filter(line => line.trim());

    const generatedTitle =
      lines?.[0]?.length < 120
        ? lines[0]
        : state.prompt;

    const cleanContent =
      rawContent
        .replace(/\*\*/g, "")
        .replace(/```/g, "")
        .replace(/###/g, "")
        .replace(/##/g, "")
        .replace(/#/g, "")
        .trim();

    const fileName =
      `pdf-${Date.now()}.pdf`;

    const doc =
      new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
        info: {
          Title: generatedTitle,
          Author: "Omnix-AI",
          Subject: state.prompt,
          Creator: "Omnix-AI PDF Agent"
        }
      });

    const chunks = [];

    doc.on("data", chunk => {
      chunks.push(chunk);
    });

    // Cover Title

    doc
      .fontSize(26)
      .fillColor("#111827")
      .text(
        generatedTitle,
        {
          align: "center"
        }
      );

    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated on ${new Date().toLocaleString()}`,
        {
          align: "center"
        }
      );

    doc.moveDown(3);

    // Content

    doc
      .fontSize(12)
      .fillColor("#374151")
      .text(
        cleanContent,
        {
          align: "left",
          lineGap: 6
        }
      );

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text(
        "Generated by Omnix-AI",
        {
          align: "center"
        }
      );

    doc.end();

    await new Promise(
      (resolve, reject) => {

        doc.on(
          "end",
          resolve
        );

        doc.on(
          "error",
          reject
        );

      }
    );

    const pdfBuffer =
      Buffer.concat(chunks);

    const { url } = await saveArtifact(
      pdfBuffer,
      fileName,
      "application/pdf",
      {
        userId: state.userId,
        conversationId: state.conversationId,
        ttlSeconds: 24 * 60 * 60,
      }
    );

    return {

      ...state,

response: `
# ✅ PDF Generated Successfully

📄 **${generatedTitle}**

📥 [Download PDF](${url})

⏳ Link expires in 24 hours.
`.trim()

    };

  } catch (error) {

    console.error("PDF Agent Error:", error);

    /**
     * Rethrown rather than turned into a friendly message.
     *
     * Credits are taken at the top of this function, and the controller only
     * refunds a run that throws. Returning a response here instead counted as
     * success, so a failed generation charged the user and kept the money —
     * the exact case the refund logic exists to prevent.
     */
    throw error;

  }

};